export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_ALERT";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const SET_ALERT ="SET_ALERT";
export const REMOVE_ALERT ="REMOVE_ALERT";
export const CLEAR_PROFILE ="CLEAR_PROFILE";

export const CREATE_SESSION ="CREATE_SESSION";
export const GET_GODS ="GET_GODS";
export const GET_GODS_FROM_LOCAL ="GET_GODS_FROM_LOCAL";
export const UPDATE_GODS ="UPDATE_GODS";
export const GET_BOTH_GOD ="GET_BOTH_GOD";
export const UPDATE_GODS_TRANSLATED_DATA ="UPDATE_GODS_TRANSLATED_DATA";
export const CLEAR_GOD_LOCAL ="CLEAR_GOD_LOCAL";
